//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : PV_ProyectoFinal
	/// Data Source    : DESKTOP-RRP2641\SQLEXPRESS
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class PvProyectoFinalDB : LinqToDB.Data.DataConnection
	{
		public ITable<Bitacora>    Bitacoras    { get { return this.GetTable<Bitacora>(); } }
		public ITable<Habitacion>  Habitacions  { get { return this.GetTable<Habitacion>(); } }
		public ITable<Hotel>       Hotels       { get { return this.GetTable<Hotel>(); } }
		public ITable<Persona>     Personas     { get { return this.GetTable<Persona>(); } }
		public ITable<Reservacion> Reservacions { get { return this.GetTable<Reservacion>(); } }

		public PvProyectoFinalDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(DataOptions<PvProyectoFinalDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Bitacora")]
	public partial class Bitacora
	{
		[Column("idBitacora"),      PrimaryKey, Identity] public int      IdBitacora      { get; set; } // int
		[Column("idReservacion"),   NotNull             ] public int      IdReservacion   { get; set; } // int
		[Column("idPersona"),       NotNull             ] public int      IdPersona       { get; set; } // int
		[Column("accionRealizada"), NotNull             ] public string   AccionRealizada { get; set; } // varchar(25)
		[Column("fechaDeLaAccion"), NotNull             ] public DateTime FechaDeLaAccion { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_Bitacora_Persona (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Persona { get; set; }

		/// <summary>
		/// FK_Bitacora_Reservacion (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdReservacion", OtherKey="IdReservacion", CanBeNull=false)]
		public Reservacion Reservacion { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Habitacion")]
	public partial class Habitacion
	{
		[Column("idHabitacion"),     PrimaryKey, Identity] public int    IdHabitacion     { get; set; } // int
		[Column("idHotel"),          NotNull             ] public int    IdHotel          { get; set; } // int
		[Column("numeroHabitacion"), NotNull             ] public string NumeroHabitacion { get; set; } // varchar(10)
		[Column("capacidadMaxima"),  NotNull             ] public int    CapacidadMaxima  { get; set; } // int
		[Column("descripcion"),      NotNull             ] public string Descripcion      { get; set; } // varchar(500)
		[Column("estado"),           NotNull             ] public char   Estado           { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Habitacion_Hotel (dbo.Hotel)
		/// </summary>
		[Association(ThisKey="IdHotel", OtherKey="IdHotel", CanBeNull=false)]
		public Hotel Hotel { get; set; }

		/// <summary>
		/// FK_Reservacion_Habitacion_BackReference (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdHabitacion", OtherKey="IdHabitacion", CanBeNull=true)]
		public IEnumerable<Reservacion> Reservacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Hotel")]
	public partial class Hotel
	{
		[Column("idHotel"),            PrimaryKey,  Identity] public int     IdHotel            { get; set; } // int
		[Column("nombre"),             NotNull              ] public string  Nombre             { get; set; } // varchar(150)
		[Column("direccion"),             Nullable          ] public string  Direccion          { get; set; } // varchar(500)
		[Column("costoPorCadaAdulto"), NotNull              ] public decimal CostoPorCadaAdulto { get; set; } // numeric(10, 2)
		[Column("costoPorCadaNinho"),  NotNull              ] public decimal CostoPorCadaNinho  { get; set; } // numeric(10, 2)

		#region Associations

		/// <summary>
		/// FK_Habitacion_Hotel_BackReference (dbo.Habitacion)
		/// </summary>
		[Association(ThisKey="IdHotel", OtherKey="IdHotel", CanBeNull=true)]
		public IEnumerable<Habitacion> Habitacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Persona")]
	public partial class Persona
	{
		[Column("idPersona"),      PrimaryKey, Identity] public int    IdPersona      { get; set; } // int
		[Column("nombreCompleto"), NotNull             ] public string NombreCompleto { get; set; } // varchar(250)
		[Column("email"),          NotNull             ] public string Email          { get; set; } // varchar(150)
		[Column("clave"),          NotNull             ] public string Clave          { get; set; } // varchar(15)
		[Column("esEmpleado"),     NotNull             ] public bool   EsEmpleado     { get; set; } // bit
		[Column("estado"),         NotNull             ] public char   Estado         { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Persona_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Reservacion_Persona_BackReference (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Reservacion> Reservacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Reservacion")]
	public partial class Reservacion
	{
		[Column("idReservacion"),        PrimaryKey,  Identity] public int       IdReservacion        { get; set; } // int
		[Column("idPersona"),            NotNull              ] public int       IdPersona            { get; set; } // int
		[Column("idHabitacion"),         NotNull              ] public int       IdHabitacion         { get; set; } // int
		[Column("fechaEntrada"),         NotNull              ] public DateTime  FechaEntrada         { get; set; } // datetime
		[Column("fechaSalida"),          NotNull              ] public DateTime  FechaSalida          { get; set; } // datetime
		[Column("numeroAdultos"),        NotNull              ] public int       NumeroAdultos        { get; set; } // int
		[Column("numeroNinhos"),         NotNull              ] public int       NumeroNinhos         { get; set; } // int
		[Column("totalDiasReservacion"), NotNull              ] public int       TotalDiasReservacion { get; set; } // int
		[Column("costoPorCadaAdulto"),   NotNull              ] public decimal   CostoPorCadaAdulto   { get; set; } // numeric(10, 2)
		[Column("costoPorCadaNinho"),    NotNull              ] public decimal   CostoPorCadaNinho    { get; set; } // numeric(10, 2)
		[Column("costoTotal"),           NotNull              ] public decimal   CostoTotal           { get; set; } // numeric(14, 2)
		[Column("fechaCreacion"),        NotNull              ] public DateTime  FechaCreacion        { get; set; } // datetime
		[Column("fechaModificacion"),       Nullable          ] public DateTime? FechaModificacion    { get; set; } // datetime
		[Column("estado"),               NotNull              ] public char      Estado               { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Reservacion_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdReservacion", OtherKey="IdReservacion", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Reservacion_Habitacion (dbo.Habitacion)
		/// </summary>
		[Association(ThisKey="IdHabitacion", OtherKey="IdHabitacion", CanBeNull=false)]
		public Habitacion Habitacion { get; set; }

		/// <summary>
		/// FK_Reservacion_Persona (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Persona { get; set; }

		#endregion
	}

	public static partial class PvProyectoFinalDBStoredProcedures
	{
		#region SpAccionEstadoUsuario

		public static int SpAccionEstadoUsuario(this PvProyectoFinalDB dataConnection, int? @idPersona, bool? @esEmpleado)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",  @idPersona,  LinqToDB.DataType.Int32),
				new DataParameter("@esEmpleado", @esEmpleado, LinqToDB.DataType.Boolean)
			};

			return dataConnection.ExecuteProc("[dbo].[spAccionEstadoUsuario]", parameters);
		}

		#endregion

		#region SpActualizarHotel

		public static int SpActualizarHotel(this PvProyectoFinalDB dataConnection, int? @idHotel, string @nombre, string @direccion, decimal? @costoPorCadaAdulto, decimal? @costoPorCadaNinho)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",            @idHotel,            LinqToDB.DataType.Int32),
				new DataParameter("@nombre",             @nombre,             LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@direccion",          @direccion,          LinqToDB.DataType.VarChar)
				{
					Size = 500
				},
				new DataParameter("@costoPorCadaAdulto", @costoPorCadaAdulto, LinqToDB.DataType.Decimal),
				new DataParameter("@costoPorCadaNinho",  @costoPorCadaNinho,  LinqToDB.DataType.Decimal)
			};

			return dataConnection.ExecuteProc("[dbo].[spActualizarHotel]", parameters);
		}

		#endregion

		#region SpAlterdiagram

		public static int SpAlterdiagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]", parameters);
		}

		#endregion

		#region SpBuscarHabitacionById

		public static IEnumerable<SpBuscarHabitacionByIdResult> SpBuscarHabitacionById(this PvProyectoFinalDB dataConnection, int? @idHabitacion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion", @idHabitacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpBuscarHabitacionByIdResult>("[dbo].[spBuscarHabitacionById]", parameters);
		}

		public partial class SpBuscarHabitacionByIdResult
		{
			                   public int    IdHabitacion     { get; set; }
			                   public int    IdHotel          { get; set; }
			                   public string Hotel            { get; set; }
			                   public string NumeroHabitacion { get; set; }
			                   public int    CapacidadMaxima  { get; set; }
			                   public string Descripcion      { get; set; }
			[Column("estado")] public char   Estado           { get; set; }
		}

		#endregion

		#region SpCancelarReservacion

		public static int SpCancelarReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion, int? @idPersonaAccion)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion",   @idReservacion,   LinqToDB.DataType.Int32),
				new DataParameter("@idPersonaAccion", @idPersonaAccion, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[spCancelarReservacion]", parameters);
		}

		#endregion

		#region SpConsultarClienteReservacion

		public static IEnumerable<SpConsultarClienteReservacionResult> SpConsultarClienteReservacion(this PvProyectoFinalDB dataConnection, int? @IdPersona)
		{
			var parameters = new []
			{
				new DataParameter("@IdPersona", @IdPersona, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarClienteReservacionResult>("[dbo].[spConsultarClienteReservacion]", parameters);
		}

		public partial class SpConsultarClienteReservacionResult
		{
			[Column("idReservacion")] public int      IdReservacion { get; set; }
			[Column("hotel")        ] public string   Hotel         { get; set; }
			[Column("fechaEntrada") ] public DateTime FechaEntrada  { get; set; }
			[Column("fechaSalida")  ] public DateTime FechaSalida   { get; set; }
			[Column("costoTotal")   ] public decimal  CostoTotal    { get; set; }
			[Column("estado")       ] public char     Estado        { get; set; }
		}

		#endregion

		#region SpConsultarGestionReservasion

		public static IEnumerable<SpConsultarGestionReservasionResult> SpConsultarGestionReservasion(this PvProyectoFinalDB dataConnection, int? @idPersona)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona", @idPersona, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarGestionReservasionResult>("[dbo].[spConsultarGestionReservasion]", parameters);
		}

		public partial class SpConsultarGestionReservasionResult
		{
			[Column("idReservacion")] public int      IdReservacion { get; set; }
			[Column("cliente")      ] public string   Cliente       { get; set; }
			[Column("hotel")        ] public string   Hotel         { get; set; }
			[Column("fechaEntrada") ] public DateTime FechaEntrada  { get; set; }
			[Column("fechaSalida")  ] public DateTime FechaSalida   { get; set; }
			[Column("costoTotal")   ] public decimal  CostoTotal    { get; set; }
			[Column("estado")       ] public char     Estado        { get; set; }
		}

		#endregion

		#region SpCrearHabitacion

		public static int SpCrearHabitacion(this PvProyectoFinalDB dataConnection, int? @idHotel, string @numeroHabitacion, int? @capacidadMaxima, string @descripcion)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",          @idHotel,          LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion", @numeroHabitacion, LinqToDB.DataType.VarChar)
				{
					Size = 10
				},
				new DataParameter("@capacidadMaxima",  @capacidadMaxima,  LinqToDB.DataType.Int32),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				}
			};

			return dataConnection.ExecuteProc("[dbo].[spCrearHabitacion]", parameters);
		}

		#endregion

		#region SpCrearPersona

		public static int SpCrearPersona(this PvProyectoFinalDB dataConnection, string @nombreCompleto, string @email, string @clave)
		{
			var parameters = new []
			{
				new DataParameter("@nombreCompleto", @nombreCompleto, LinqToDB.DataType.VarChar)
				{
					Size = 250
				},
				new DataParameter("@email",          @email,          LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@clave",          @clave,          LinqToDB.DataType.VarChar)
				{
					Size = 15
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_CrearPersona]", parameters);
		}

		#endregion

		#region SpCrearReservacion

		public static int SpCrearReservacion(this PvProyectoFinalDB dataConnection, int? @idPersona, int? @idHabitacion, DateTime? @fechaEntrada, DateTime? @fechaSalida, int? @numeroNinhos, int? @numeroAdultos, decimal? @costoPorCadaAdulto, decimal? @costoPorCadaNinho, int? @idPersonaAccion)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",          @idPersona,          LinqToDB.DataType.Int32),
				new DataParameter("@idHabitacion",       @idHabitacion,       LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",       @fechaEntrada,       LinqToDB.DataType.DateTime),
				new DataParameter("@fechaSalida",        @fechaSalida,        LinqToDB.DataType.DateTime),
				new DataParameter("@numeroNinhos",       @numeroNinhos,       LinqToDB.DataType.Int32),
				new DataParameter("@numeroAdultos",      @numeroAdultos,      LinqToDB.DataType.Int32),
				new DataParameter("@costoPorCadaAdulto", @costoPorCadaAdulto, LinqToDB.DataType.Decimal),
				new DataParameter("@costoPorCadaNinho",  @costoPorCadaNinho,  LinqToDB.DataType.Decimal),
				new DataParameter("@idPersonaAccion",    @idPersonaAccion,    LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[spCrearReservacion]", parameters);
		}

		#endregion

		#region SpCreatediagram

		public static int SpCreatediagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]", parameters);
		}

		#endregion

		#region SpDropdiagram

		public static int SpDropdiagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]", parameters);
		}

		#endregion

		#region SpEditarHabitacion

		public static int SpEditarHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion, int? @idHotel, string @numeroHabitacion, int? @capacidadMaxima, string @descripcion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion",     @idHabitacion,     LinqToDB.DataType.Int32),
				new DataParameter("@idHotel",          @idHotel,          LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion", @numeroHabitacion, LinqToDB.DataType.VarChar)
				{
					Size = 50
				},
				new DataParameter("@capacidadMaxima",  @capacidadMaxima,  LinqToDB.DataType.Int32),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				}
			};

			return dataConnection.ExecuteProc("[dbo].[spEditarHabitacion]", parameters);
		}

		#endregion

		#region SpEditarReservacion

		public static int SpEditarReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion, DateTime? @fechaEntrada, DateTime? @fechaSalida, int? @numeroAdultos, int? @numeroNinhos, int? @idPersonaAccion)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion",   @idReservacion,   LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",    @fechaEntrada,    LinqToDB.DataType.DateTime),
				new DataParameter("@fechaSalida",     @fechaSalida,     LinqToDB.DataType.DateTime),
				new DataParameter("@numeroAdultos",   @numeroAdultos,   LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",    @numeroNinhos,    LinqToDB.DataType.Int32),
				new DataParameter("@idPersonaAccion", @idPersonaAccion, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[spEditarReservacion]", parameters);
		}

		#endregion

		#region SpFiltroClientes

		public static IEnumerable<SpFiltroClientesResult> SpFiltroClientes(this PvProyectoFinalDB dataConnection, int? @idEmpleado)
		{
			var parameters = new []
			{
				new DataParameter("@idEmpleado", @idEmpleado, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpFiltroClientesResult>("[dbo].[spFiltroClientes]", parameters);
		}

		public partial class SpFiltroClientesResult
		{
			[Column("idPersona")     ] public int    IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
		}

		#endregion

		#region SpFiltroReservaciones

		public static IEnumerable<SpFiltroReservacionesResult> SpFiltroReservaciones(this PvProyectoFinalDB dataConnection, int? @idCliente, DateTime? @fechaEntrada, DateTime? @fechaSalida)
		{
			var parameters = new []
			{
				new DataParameter("@idCliente",    @idCliente,    LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada", @fechaEntrada, LinqToDB.DataType.Date),
				new DataParameter("@fechaSalida",  @fechaSalida,  LinqToDB.DataType.Date)
			};

			return dataConnection.QueryProc<SpFiltroReservacionesResult>("[dbo].[spFiltroReservaciones]", parameters);
		}

		public partial class SpFiltroReservacionesResult
		{
			[Column("idReservacion")] public int      IdReservacion { get; set; }
			[Column("cliente")      ] public string   Cliente       { get; set; }
			[Column("hotel")        ] public string   Hotel         { get; set; }
			[Column("fechaEntrada") ] public DateTime FechaEntrada  { get; set; }
			[Column("fechaSalida")  ] public DateTime FechaSalida   { get; set; }
			[Column("costoTotal")   ] public decimal  CostoTotal    { get; set; }
			[Column("estado")       ] public char     Estado        { get; set; }
		}

		#endregion

		#region SpHelpdiagramdefinition

		public static IEnumerable<SpHelpdiagramdefinitionResult> SpHelpdiagramdefinition(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]", parameters);
		}

		public partial class SpHelpdiagramdefinitionResult
		{
			[Column("version")   ] public int?   Version    { get; set; }
			[Column("definition")] public byte[] Definition { get; set; }
		}

		#endregion

		#region SpHelpdiagrams

		public static IEnumerable<SpHelpdiagramsResult> SpHelpdiagrams(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramsResult>("[dbo].[sp_helpdiagrams]", parameters);
		}

		public partial class SpHelpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region SpInactivarHabitacion

		public static int SpInactivarHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion", @idHabitacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[spInactivarHabitacion]", parameters);
		}

		#endregion

		#region SpInsertarHotel

		public static int SpInsertarHotel(this PvProyectoFinalDB dataConnection, string @nombre, string @direccion, decimal? @costoPorCadaAdulto, decimal? @costoPorCadaNinho)
		{
			var parameters = new []
			{
				new DataParameter("@nombre",             @nombre,             LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@direccion",          @direccion,          LinqToDB.DataType.VarChar)
				{
					Size = 500
				},
				new DataParameter("@costoPorCadaAdulto", @costoPorCadaAdulto, LinqToDB.DataType.Decimal),
				new DataParameter("@costoPorCadaNinho",  @costoPorCadaNinho,  LinqToDB.DataType.Decimal)
			};

			return dataConnection.ExecuteProc("[dbo].[SP_InsertarHotel]", parameters);
		}

		#endregion

		#region SpListarHabitaciones

		public static IEnumerable<SpListarHabitacionesResult> SpListarHabitaciones(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpListarHabitacionesResult>("[dbo].[spListarHabitaciones]");
		}

		public partial class SpListarHabitacionesResult
		{
			[Column("idHabitacion")    ] public int    IdHabitacion     { get; set; }
			                             public string Nombre           { get; set; }
			[Column("numeroHabitacion")] public string NumeroHabitacion { get; set; }
			[Column("capacidadMaxima") ] public int    CapacidadMaxima  { get; set; }
			[Column("estado")          ] public char   Estado           { get; set; }
		}

		#endregion

		#region SpListarHoteles

		public static IEnumerable<Hotel> SpListarHoteles(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<Hotel>("[dbo].[spListarHoteles]");
		}

		#endregion

		#region SpListarUsuarios

		public static IEnumerable<SpListarUsuariosResult> SpListarUsuarios(this PvProyectoFinalDB dataConnection, bool? @esEmpleado, int? @idPersona)
		{
			var parameters = new []
			{
				new DataParameter("@esEmpleado", @esEmpleado, LinqToDB.DataType.Boolean),
				new DataParameter("@idPersona",  @idPersona,  LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpListarUsuariosResult>("[dbo].[spListarUsuarios]", parameters);
		}

		public partial class SpListarUsuariosResult
		{
			[Column("idPersona")     ] public int    IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
			[Column("esEmpleado")    ] public bool   EsEmpleado     { get; set; }
			[Column("estado")        ] public char   Estado         { get; set; }
		}

		#endregion

		#region SpLOGIN

		public static int SpLOGIN(this PvProyectoFinalDB dataConnection, string @email, string @clave, ref int? @idPersona, ref bool? @esEmpleado, ref int? @acceso, ref string @nombreCompleto)
		{
			var parameters = new []
			{
				new DataParameter("@email",          @email,          LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@clave",          @clave,          LinqToDB.DataType.VarChar)
				{
					Size = 15
				},
				new DataParameter("@idPersona",      @idPersona,      LinqToDB.DataType.Int32)
				{
					Direction = ParameterDirection.InputOutput
				},
				new DataParameter("@esEmpleado",     @esEmpleado,     LinqToDB.DataType.Boolean)
				{
					Direction = ParameterDirection.InputOutput
				},
				new DataParameter("@acceso",         @acceso,         LinqToDB.DataType.Int32)
				{
					Direction = ParameterDirection.InputOutput
				},
				new DataParameter("@nombreCompleto", @nombreCompleto, LinqToDB.DataType.VarChar)
				{
					Direction = ParameterDirection.InputOutput,
					Size      = 250
				}
			};

			var ret = dataConnection.ExecuteProc("[dbo].[spLOGIN]", parameters);

			@idPersona      = Converter.ChangeTypeTo<int?>  (parameters[2].Value);
			@esEmpleado     = Converter.ChangeTypeTo<bool?> (parameters[3].Value);
			@acceso         = Converter.ChangeTypeTo<int?>  (parameters[4].Value);
			@nombreCompleto = Converter.ChangeTypeTo<string>(parameters[5].Value);

			return ret;
		}

		#endregion

		#region SpModificarPersona

		public static int SpModificarPersona(this PvProyectoFinalDB dataConnection, int? @idPersona, string @nombreCompleto, string @email, string @clave)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",      @idPersona,      LinqToDB.DataType.Int32),
				new DataParameter("@nombreCompleto", @nombreCompleto, LinqToDB.DataType.VarChar)
				{
					Size = 250
				},
				new DataParameter("@email",          @email,          LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@clave",          @clave,          LinqToDB.DataType.VarChar)
				{
					Size = 15
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_ModificarPersona]", parameters);
		}

		#endregion

		#region SpObtenerBitacoraById

		public static IEnumerable<SpObtenerBitacoraByIdResult> SpObtenerBitacoraById(this PvProyectoFinalDB dataConnection, int? @idReservacion)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion", @idReservacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerBitacoraByIdResult>("[dbo].[spObtenerBitacoraById]", parameters);
		}

		public partial class SpObtenerBitacoraByIdResult
		{
			[Column("fechaDeLaAccion")] public DateTime FechaDeLaAccion { get; set; }
			[Column("accionRealizada")] public string   AccionRealizada { get; set; }
			[Column("nombreCompleto") ] public string   NombreCompleto  { get; set; }
		}

		#endregion

		#region SpObtenerCientes

		public static IEnumerable<SpObtenerCientesResult> SpObtenerCientes(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerCientesResult>("[dbo].[spObtenerCientes]");
		}

		public partial class SpObtenerCientesResult
		{
			[Column("idPersona")     ] public int    IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
		}

		#endregion

		#region SpObtenerCostosyHabitacion

		public static IEnumerable<SpObtenerCostosyHabitacionResult> SpObtenerCostosyHabitacion(this PvProyectoFinalDB dataConnection, int? @idHotel, int? @personasTotal, DateTime? @fechaEntrada, DateTime? @fechaSalida)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",       @idHotel,       LinqToDB.DataType.Int32),
				new DataParameter("@personasTotal", @personasTotal, LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",  @fechaEntrada,  LinqToDB.DataType.Date),
				new DataParameter("@fechaSalida",   @fechaSalida,   LinqToDB.DataType.Date)
			};

			return dataConnection.QueryProc<SpObtenerCostosyHabitacionResult>("[dbo].[spObtenerCostosyHabitacion]", parameters);
		}

		public partial class SpObtenerCostosyHabitacionResult
		{
			[Column("costoPorCadaAdulto")] public decimal CostoPorCadaAdulto { get; set; }
			[Column("costoPorCadaNinho") ] public decimal CostoPorCadaNinho  { get; set; }
			[Column("capacidadMaxima")   ] public int     CapacidadMaxima    { get; set; }
			[Column("idHabitacion")      ] public int     IdHabitacion       { get; set; }
		}

		#endregion

		#region SpObtenerHoteles

		public static IEnumerable<SpObtenerHotelesResult> SpObtenerHoteles(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerHotelesResult>("[dbo].[spObtenerHoteles]");
		}

		public partial class SpObtenerHotelesResult
		{
			[Column("idHotel")] public int    IdHotel { get; set; }
			[Column("nombre") ] public string Nombre  { get; set; }
		}

		#endregion

		#region SpObtenerHotelPorId

		public static IEnumerable<Hotel> SpObtenerHotelPorId(this PvProyectoFinalDB dataConnection, int? @idHotel)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel", @idHotel, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<Hotel>("[dbo].[SP_ObtenerHotelPorId]", parameters);
		}

		#endregion

		#region SpObtenerReservacionById

		public static IEnumerable<SpObtenerReservacionByIdResult> SpObtenerReservacionById(this PvProyectoFinalDB dataConnection, int? @idReservacion, int? @idPersona, bool? @esEmpleado)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion", @idReservacion, LinqToDB.DataType.Int32),
				new DataParameter("@idPersona",     @idPersona,     LinqToDB.DataType.Int32),
				new DataParameter("@esEmpleado",    @esEmpleado,    LinqToDB.DataType.Boolean)
			};

			return dataConnection.QueryProc<SpObtenerReservacionByIdResult>("[dbo].[spObtenerReservacionById]", parameters);
		}

		public partial class SpObtenerReservacionByIdResult
		{
			[Column("idReservacion")       ] public int      IdReservacion        { get; set; }
			[Column("idPersona")           ] public int      IdPersona            { get; set; }
			[Column("hotel")               ] public string   Hotel                { get; set; }
			[Column("capacidadMaxima")     ] public int      CapacidadMaxima      { get; set; }
			[Column("numeroHabitacion")    ] public string   NumeroHabitacion     { get; set; }
			[Column("cliente")             ] public string   Cliente              { get; set; }
			[Column("fechaEntrada")        ] public DateTime FechaEntrada         { get; set; }
			[Column("fechaSalida")         ] public DateTime FechaSalida          { get; set; }
			[Column("totalDiasReservacion")] public int      TotalDiasReservacion { get; set; }
			[Column("numeroNinhos")        ] public int      NumeroNinhos         { get; set; }
			[Column("numeroAdultos")       ] public int      NumeroAdultos        { get; set; }
			[Column("costoTotal")          ] public decimal  CostoTotal           { get; set; }
			[Column("estado")              ] public char     Estado               { get; set; }
		}

		#endregion

		#region SpRenamediagram

		public static int SpRenamediagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, string @newDiagramname)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname",     @diagramname,    LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",        @ownerId,        LinqToDB.DataType.Int32),
				new DataParameter("@new_diagramname", @newDiagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]", parameters);
		}

		#endregion

		#region SpUpgraddiagrams

		public static int SpUpgraddiagrams(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_upgraddiagrams]");
		}

		#endregion

		#region SpValidarHabitacion

		public static IEnumerable<SpValidarHabitacionResult> SpValidarHabitacion(this PvProyectoFinalDB dataConnection, int? @idHotel, string @numeroHabitacion)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",          @idHotel,          LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion", @numeroHabitacion, LinqToDB.DataType.VarChar)
				{
					Size = 10
				}
			};

			return dataConnection.QueryProc<SpValidarHabitacionResult>("[dbo].[spValidarHabitacion]", parameters);
		}

		public partial class SpValidarHabitacionResult
		{
			public int? Existe { get; set; }
		}

		#endregion

		#region SpValidarHotel

		public static IEnumerable<SpValidarHotelResult> SpValidarHotel(this PvProyectoFinalDB dataConnection, string @nombre)
		{
			var parameters = new []
			{
				new DataParameter("@nombre", @nombre, LinqToDB.DataType.VarChar)
				{
					Size = 150
				}
			};

			return dataConnection.QueryProc<SpValidarHotelResult>("[dbo].[spValidarHotel]", parameters);
		}

		public partial class SpValidarHotelResult
		{
			public int? Existe { get; set; }
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region FnDiagramobjects

		[Sql.Function(Name="[dbo].[fn_diagramobjects]", ServerSideOnly=true)]
		public static int? FnDiagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Bitacora Find(this ITable<Bitacora> table, int IdBitacora)
		{
			return table.FirstOrDefault(t =>
				t.IdBitacora == IdBitacora);
		}

		public static Habitacion Find(this ITable<Habitacion> table, int IdHabitacion)
		{
			return table.FirstOrDefault(t =>
				t.IdHabitacion == IdHabitacion);
		}

		public static Hotel Find(this ITable<Hotel> table, int IdHotel)
		{
			return table.FirstOrDefault(t =>
				t.IdHotel == IdHotel);
		}

		public static Persona Find(this ITable<Persona> table, int IdPersona)
		{
			return table.FirstOrDefault(t =>
				t.IdPersona == IdPersona);
		}

		public static Reservacion Find(this ITable<Reservacion> table, int IdReservacion)
		{
			return table.FirstOrDefault(t =>
				t.IdReservacion == IdReservacion);
		}
	}
}
